spring:
  application:
    name: escala-do-reino

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        tenant_identifier_resolver: com.nathannolacio.escala_do_reino_backend.core.config.TenantIdentifierResolver

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: c2VjcmV0S2V5Rm9ySldUV2l0aEF0TGVhc3QzMkJ5dGVzIQ==